### ISSUE TITLE
TypeError: Cannot find function replace in object 9. (line 51, file "main")

### ISSUE THREAD

**Issue by poojaalagar** [tanabee/okr-tree#1]
![issue](https://user-images.githubusercontent.com/38976692/62538511-a1170880-b870-11e9-8c61-5ad2a695f40f.png)

cant able to run the script due to this error.

**Comment by tanabee** [comment]
I could do it by following the procedure described in Qiita.
https://qiita.com/tanabee/items/3c17dcdbb8efb7afe212

Is it possible to share the data in the spreadsheet? You can mask some data if needed.

**Comment by poojaalagar** [comment]
i have attached link for a sample excel sheet for reference 

https://docs.google.com/spreadsheets/d/1xqPkgIAatsf8R1L3JzLCGcRUDFJwAEryWdCggHvSGj4/edit?usp=sharing

**Comment by tanabee** [comment]
Thank you! I requested access to the Spreadsheet.

**Comment by poojaalagar** [comment]
given access , that error is not occurring but the tree is not populated

**Comment by tanabee** [comment]
Thank you.
I understand the problem. You should not change the columns.

- 1st column must be Organization ID
- 2nd: Organization name
- 3rd: Parent organization ID
- 4th: Objective
- 5th: Key Results

Please try to copy the template spreadsheet and edit the values after 2nd row.

https://docs.google.com/spreadsheets/d/1E0zNbc-PzhBq2e5N2aqNttRd-7QohN6n4AOfZhX64b0/copy

![okr-tree](https://user-images.githubusercontent.com/2603644/62916819-f739fd80-bdd4-11e9-83e8-a32a14fb256e.png)
